//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconstrucoes
    {
        public int Id { get; set; }
        public string Informacoes { get; set; }
        public System.DateTime DataHora { get; set; }
        public string Arquivo { get; set; }
    }
}
